export const restaurants = [
	{
		id: 0,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 1,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 2,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 3,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 4,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 5,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 6,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 7,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 8,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 9,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
	{
		id: 10,
		name: 'Pizza Hut',
		image: 'https://bonsplansmaroc.com/wp-content/uploads/2020/03/image-pizza-hut-2.jpg',
		favorites: 246,
		timeBetween: [ 25, 35 ],
		categories: [ 'Pizza', 'Moroccan', 'Fast Food' ],
	},
] as any[]
